package com.parlour.management;
import static com.parlour.management.Db.*;
import java.util.*;
import java.time.*;
import java.sql.Timestamp;
import java.math.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.*;
import org.springframework.beans.factory.annotation.Value;
@RestController
public class Bookings {
 final Db db;final Auth auth;final Catalog catalog;final Availability availability;final ObjectMapper json;final boolean paymentConfigured;
 Bookings(Db db,Auth auth,Catalog catalog,Availability availability,ObjectMapper json,@Value("${app.ssl-store-id}")String store,@Value("${app.ssl-store-password}")String pass){this.db=db;this.auth=auth;this.catalog=catalog;this.availability=availability;this.json=json;paymentConfigured=!store.isBlank()&&!pass.isBlank();}
 record Create(long parlour_id,List<Long> services,Long staff_id,Instant start_at,String customer_name,String customer_phone,String payment_method){}
 String encode(Object x){try{return json.writeValueAsString(x);}catch(Exception e){throw new IllegalStateException(e);}}
 @PostMapping("/api/bookings") @Transactional(isolation=Isolation.READ_COMMITTED) Map<String,Object> create(@RequestBody Create b,@RequestHeader("Idempotency-Key")String key){long uid=id(auth.current(),"user_id");if(!"CUSTOMER".equals(auth.current().get("role")))throw error(403,"Use customer mode for booking");return reserve(b,key,uid,false);}
 Map<String,Object> reserve(Create b,String key,long uid,boolean walkIn){if(key.isBlank()||key.length()>100||b.start_at()==null||b.customer_name()==null||b.customer_name().isBlank()||b.customer_name().length()>120||b.customer_phone()==null||!b.customer_phone().matches("\\+?[0-9 ()-]{7,25}"))throw error(400,"Invalid booking details");String hash;try{hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(encode(b).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}
  catalog.lock(b.parlour_id());var prior=db.list("SELECT * FROM bookings WHERE customer_id=? AND idempotency_key=?",uid,key);if(!prior.isEmpty()){if(!hash.equals(prior.get(0).get("request_hash")))throw error(409,"Idempotency key was used for different details");return detail(id(prior.get(0),"booking_id"));}
  var parlour=catalog.verified(b.parlour_id());var selected=availability.selection(b.parlour_id(),b.services());var policy=db.one("SELECT * FROM cancellation_policies WHERE parlour_id=?",b.parlour_id());Long staff=availability.choose(b.parlour_id(),b.services(),b.staff_id(),b.start_at(),selected.minutes(),0);if(staff==null)throw error(409,"That slot is no longer available");
  boolean online="ONLINE".equals(b.payment_method());if(!online&&!"AT_PARLOUR".equals(b.payment_method()))throw error(400,"Choose ONLINE or AT_PARLOUR");if(yes(policy.get("advance_required"))&&!online)throw error(400,"This parlour requires advance payment");if(online&&!paymentConfigured)throw error(503,"Online payments are not configured yet");BigDecimal advance=online?selected.total().multiply(new BigDecimal(yes(policy.get("advance_required"))?policy.get("min_advance_pct").toString():"100")).divide(new BigDecimal(100),2,RoundingMode.HALF_UP):BigDecimal.ZERO;
  if(online&&advance.signum()<=0)throw error(400,"Online payment requires a positive amount");String status=online?"PENDING_PAYMENT":yes(policy.get("owner_approval"))&&!walkIn?"PENDING_OWNER":"CONFIRMED";
  long id=db.insert("bookings",map("customer_name",b.customer_name().trim(),"customer_phone",b.customer_phone(),"customer_id",uid,"parlour_id",b.parlour_id(),"staff_id",staff,"booking_date",java.sql.Date.valueOf(b.start_at().atZone(ZoneId.of(parlour.get("timezone").toString())).toLocalDate()),"start_at",Timestamp.from(b.start_at()),"end_at",Timestamp.from(b.start_at().plusSeconds(selected.minutes()*60L)),"total_amount",selected.total(),"advance_amount",advance,"status",status,"idempotency_key",key,"request_hash",hash,"hold_until",online?Timestamp.from(Instant.now().plusSeconds(900)):null,"policy_snapshot",encode(policy)));
  for(var s:selected.services())db.insert("booking_items",map("booking_id",id,"service_id",id(s,"service_id"),"price",s.get("price"),"duration_min",s.get("duration_min")));event(id,"BOOKING_CREATED","Appointment created",status);return detail(id);
 }
 Map<String,Object> accessible(long bid){var b=db.one("SELECT * FROM bookings WHERE booking_id=?",bid);var u=auth.current();long uid=id(u,"user_id");if("ADMIN".equals(u.get("role")))return b;if("OWNER".equals(u.get("role"))){auth.owner(id(b,"parlour_id"));return b;}if(uid!=id(b,"customer_id"))throw error(403,"Not your booking");return b;}
 Map<String,Object> detail(long bid){var b=accessible(bid);b.remove("request_hash");b.remove("idempotency_key");b.put("items",db.list("SELECT i.*,s.name FROM booking_items i JOIN services s ON s.service_id=i.service_id WHERE i.booking_id=?",bid));b.put("payments",db.list("SELECT payment_id,transaction_id,amount,method,gateway,status,paid_at FROM payments WHERE booking_id=?",bid));return b;}
 @GetMapping("/api/bookings/{bid}") Map<String,Object> get(@PathVariable long bid){return detail(bid);}
 @GetMapping("/api/bookings") List<Map<String,Object>> mine(){long uid=id(auth.current(),"user_id");return db.list("SELECT b.*,p.name AS parlour_name FROM bookings b JOIN parlours p ON p.parlour_id=b.parlour_id WHERE customer_id=? ORDER BY start_at DESC LIMIT 200",uid);}
 Map<String,Object> locked(long bid){var b=accessible(bid);catalog.lock(id(b,"parlour_id"));return accessible(bid);}
 @SuppressWarnings("unchecked") Map<String,Object> policy(Map<String,Object>b){try{return json.readValue(b.get("policy_snapshot").toString(),Map.class);}catch(Exception e){throw new IllegalStateException(e);}}
 static Instant instant(Object x){return x instanceof Timestamp t?t.toInstant():Instant.parse(x.toString());}
 void mutable(Map<String,Object>b){if(!Set.of("PENDING_PAYMENT","PENDING_OWNER","CONFIRMED").contains(b.get("status"))||!instant(b.get("start_at")).isAfter(Instant.now()))throw error(409,"This booking can no longer be changed");}
 @PostMapping("/api/bookings/{bid}/cancel") @Transactional(isolation=Isolation.READ_COMMITTED) Map<String,Object> cancel(@PathVariable long bid){var b=locked(bid);if(Set.of("CANCELLED","CANCEL_PENDING").contains(b.get("status")))return detail(bid);mutable(b);var p=policy(b);boolean timely=!Instant.now().isAfter(instant(b.get("start_at")).minusSeconds(((Number)p.get("cancel_window_hr")).longValue()*3600));BigDecimal paid=paid(bid);BigDecimal refund=paid.multiply(money(p.get("refund_pct"))).divide(new BigDecimal(100),2,RoundingMode.DOWN);if(!timely)refund=refund.subtract(money(b.get("total_amount")).multiply(money(p.get("fee_pct"))).divide(new BigDecimal(100),2,RoundingMode.UP)).max(BigDecimal.ZERO);db.update("UPDATE bookings SET cancel_refund_quote=? WHERE booking_id=?",refund,bid);if(yes(p.get("manual_approval"))){db.update("UPDATE bookings SET status='CANCEL_PENDING' WHERE booking_id=?",bid);event(bid,"CANCEL_PENDING","Cancellation requested","Owner approval is required");}else cancelNow(bid,refund);return detail(bid);}
 BigDecimal paid(long bid){return money(db.one("SELECT COALESCE(SUM(amount),0) AS amount FROM payments WHERE booking_id=? AND status='PAID'",bid).get("amount"));}
 void cancelNow(long bid,BigDecimal refund){db.update("UPDATE bookings SET status='CANCELLED' WHERE booking_id=?",bid);queueRefund(bid,refund,"Booking cancelled");event(bid,"CANCELLED","Appointment cancelled","Eligible refund: BDT "+refund);}
 void queueRefund(long bid,BigDecimal remaining,String reason){for(var p:db.list("SELECT * FROM payments WHERE booking_id=? AND status='PAID' ORDER BY payment_id",bid)){BigDecimal amount=remaining.min(money(p.get("amount")));if(amount.signum()>0&&db.count("SELECT COUNT(*) FROM refund_requests WHERE payment_id=?",id(p,"payment_id"))==0){db.insert("refund_requests",map("payment_id",id(p,"payment_id"),"amount",amount,"reason",reason));remaining=remaining.subtract(amount);}}}
 record Move(Instant start_at,Long staff_id){}
 @PostMapping("/api/bookings/{bid}/reschedule") @Transactional(isolation=Isolation.READ_COMMITTED) Map<String,Object> move(@PathVariable long bid,@RequestBody Move move){var b=locked(bid);mutable(b);var p=policy(b);if(!"CONFIRMED".equals(b.get("status"))||!"ALLOWED".equals(p.get("reschedule_rule"))||Instant.now().isAfter(instant(b.get("start_at")).minusSeconds(((Number)p.get("cancel_window_hr")).longValue()*3600)))throw error(409,"Rescheduling is outside the policy");var ids=db.list("SELECT service_id FROM booking_items WHERE booking_id=?",bid).stream().map(r->id(r,"service_id")).toList();int duration=(int)Duration.between(instant(b.get("start_at")),instant(b.get("end_at"))).toMinutes();long pid=id(b,"parlour_id");catalog.verified(pid);availability.selection(pid,ids);Long sid=availability.choose(pid,ids,move.staff_id(),move.start_at(),duration,bid);if(sid==null)throw error(409,"New slot unavailable");var zone=ZoneId.of(db.one("SELECT timezone FROM parlours WHERE parlour_id=?",pid).get("timezone").toString());db.update("UPDATE bookings SET staff_id=?,start_at=?,end_at=?,booking_date=? WHERE booking_id=?",sid,Timestamp.from(move.start_at()),Timestamp.from(move.start_at().plusSeconds(duration*60L)),java.sql.Date.valueOf(move.start_at().atZone(zone).toLocalDate()),bid);event(bid,"RESCHEDULED","Appointment rescheduled",move.start_at().toString());return detail(bid);}
 @GetMapping("/api/owner/bookings") List<Map<String,Object>> ownerBookings(){return db.list("SELECT b.* FROM bookings b JOIN parlours p ON p.parlour_id=b.parlour_id WHERE p.owner_id=? ORDER BY start_at DESC LIMIT 300",auth.require("OWNER"));}
 @PostMapping("/api/owner/bookings/{bid}/status") @Transactional(isolation=Isolation.READ_COMMITTED) Map<String,Object> status(@PathVariable long bid,@RequestBody Map<String,Object>body){auth.require("OWNER");var b=locked(bid);String next=text(body,"status",24),old=b.get("status").toString();if(next.equals(old))return detail(bid);
  if(old.equals("PENDING_OWNER")&&next.equals("CONFIRMED")&&instant(b.get("start_at")).isAfter(Instant.now()))db.update("UPDATE bookings SET status=? WHERE booking_id=?",next,bid);
  else if(old.equals("PENDING_OWNER")&&next.equals("REJECTED")){db.update("UPDATE bookings SET status=? WHERE booking_id=?",next,bid);queueRefund(bid,paid(bid),"Owner rejected appointment");}
  else if(old.equals("CONFIRMED")&&next.equals("COMPLETED")&&!instant(b.get("end_at")).isAfter(Instant.now()))db.update("UPDATE bookings SET status=? WHERE booking_id=?",next,bid);
  else if(old.equals("CANCEL_PENDING")&&next.equals("CANCELLED"))cancelNow(bid,money(b.get("cancel_refund_quote")));
  else throw error(409,"Invalid booking transition");event(bid,next,"Booking updated",next);return detail(bid);
 }
 @PostMapping("/api/ratings") @Transactional(isolation=Isolation.READ_COMMITTED) Map<String,Object> rate(@RequestBody Map<String,Object>b){long bid=Long.parseLong(b.get("booking_id").toString());var booking=locked(bid);if(id(booking,"customer_id")!=id(auth.current(),"user_id")||!"COMPLETED".equals(booking.get("status")))throw error(403,"Only this completed booking's customer can review");String target=text(b,"target_type",16);if(!Set.of("PARLOUR","STAFF").contains(target))throw error(400,"Invalid review target");int score=Integer.parseInt(b.get("score").toString());if(score<1||score>5)throw error(400,"Score must be 1–5");long pid=id(booking,"parlour_id");Long sid=target.equals("STAFF")?id(booking,"staff_id"):null;long rid=db.insert("ratings",map("booking_id",bid,"parlour_id",pid,"staff_id",sid,"target_type",target,"score",score,"review",text(b,"review",2000)));if(sid==null)db.update("UPDATE parlours SET rating=(SELECT AVG(score) FROM ratings WHERE parlour_id=? AND target_type='PARLOUR') WHERE parlour_id=?",pid,pid);else db.update("UPDATE staff SET rating=(SELECT AVG(score) FROM ratings WHERE staff_id=? AND target_type='STAFF') WHERE staff_id=?",sid,sid);return map("rating_id",rid);}
 void event(long bid,String type,String title,String body){var b=db.one("SELECT b.customer_id,p.owner_id FROM bookings b JOIN parlours p ON p.parlour_id=b.parlour_id WHERE booking_id=?",bid);for(String key:List.of("customer_id","owner_id"))db.insert("notifications",map("user_id",id(b,key),"booking_id",bid,"type",type,"title",title,"body",body));}
}
