package com.parlour.management;
import static com.parlour.management.Db.*;
import java.util.*;
import java.time.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
@RestController
public class Catalog {
 final Db db;final Auth auth;
 Catalog(Db db,Auth auth){this.db=db;this.auth=auth;}
 record Resource(String pk,List<String> fields){}
 static final Map<String,Resource> RESOURCES=Map.ofEntries(
 entry("services","service_id","name description duration_min price status"),entry("staff","staff_id","name designation experience specialization status"),entry("business_hours","hours_id","day_of_week start_time end_time"),entry("staff_schedules","schedule_id","staff_id day_of_week start_time end_time status"),entry("holidays","holiday_id","holiday_date reason"),entry("blocked_slots","block_id","staff_id start_at end_at reason"),entry("parlour_images","image_id","image_url type sort_order"),entry("cancellation_policies","policy_id","advance_required min_advance_pct cancel_window_hr fee_pct refund_pct reschedule_rule manual_approval owner_approval")
 );
 static Map.Entry<String,Resource> entry(String t,String pk,String fields){return Map.entry(t,new Resource(pk,List.of(fields.split(" "))));}
 Resource resource(String name){var r=RESOURCES.get(name);if(r==null)throw error(404,"Unknown resource");return r;}
 @GetMapping("/api/public/health") Map<String,Object> health(){return map("status","UP","database",db.count("SELECT COUNT(*) FROM users")>=0?"UP":"DOWN");}
 @GetMapping("/api/public/parlours") List<Map<String,Object>> search(@RequestParam(defaultValue="")String q,@RequestParam(defaultValue="")String category,@RequestParam(defaultValue="rating")String sort,@RequestParam(required=false)Double lat,@RequestParam(required=false)Double lng,@RequestParam(defaultValue="10")double radius){
  if(q.length()>160||radius<1||radius>100||(lat==null)!=(lng==null)||lat!=null&&(Math.abs(lat)>90||Math.abs(lng)>180))throw error(400,"Invalid search");
  var rows=db.list("SELECT p.*, (SELECT MIN(price) FROM services s WHERE s.parlour_id=p.parlour_id AND s.status='ACTIVE') AS starting_price,(SELECT COUNT(*) FROM bookings b WHERE b.parlour_id=p.parlour_id AND b.status='COMPLETED') AS popularity,(SELECT image_url FROM parlour_images i WHERE i.parlour_id=p.parlour_id ORDER BY sort_order,image_id LIMIT 1) AS cover_image FROM parlours p WHERE p.status='VERIFIED' AND (LOWER(p.name) LIKE ? OR LOWER(p.address) LIKE ?) AND (?='' OR category=?) LIMIT 500","%"+q.toLowerCase(Locale.ROOT)+"%","%"+q.toLowerCase(Locale.ROOT)+"%",category,category);
  if(lat!=null){rows.forEach(r->r.put("distance_km",distance(lat,lng,((Number)r.get("lat")).doubleValue(),((Number)r.get("lng")).doubleValue())));rows.removeIf(r->(double)r.get("distance_km")>radius);}
  Comparator<Map<String,Object>> cmp=switch(sort){case "price"->Comparator.comparingDouble(r->r.get("starting_price")==null?Double.MAX_VALUE:((Number)r.get("starting_price")).doubleValue());case "distance"->Comparator.comparingDouble(r->r.get("distance_km")==null?0:(double)r.get("distance_km"));case "popularity"->Comparator.<Map<String,Object>>comparingLong(r->id(r,"popularity")).reversed();default->Comparator.<Map<String,Object>>comparingDouble(r->((Number)r.get("rating")).doubleValue()).reversed();};rows.sort(cmp);return rows;
 }
 static double distance(double a,double b,double c,double d){double x=Math.pow(Math.sin(Math.toRadians(c-a)/2),2)+Math.cos(Math.toRadians(a))*Math.cos(Math.toRadians(c))*Math.pow(Math.sin(Math.toRadians(d-b)/2),2);return 6371*2*Math.asin(Math.sqrt(Math.min(1,x)));}
 Map<String,Object> verified(long pid){return db.one("SELECT * FROM parlours WHERE parlour_id=? AND status='VERIFIED'",pid);}
 @GetMapping("/api/public/parlours/{pid}") Map<String,Object> profile(@PathVariable long pid){var p=verified(pid);for(String table:List.of("services","staff","business_hours","parlour_images","cancellation_policies","ratings")){String extra=List.of("services","staff").contains(table)?" AND status='ACTIVE'":"";p.put(table,db.list("SELECT * FROM "+table+" WHERE parlour_id=?"+extra,pid));}return p;}
 @GetMapping("/api/owner/parlours") List<Map<String,Object>> owned(){return db.list("SELECT * FROM parlours WHERE owner_id=?",auth.require("OWNER"));}
 @PostMapping("/api/owner/parlours") @Transactional Map<String,Object> create(@RequestBody Map<String,Object>b){long uid=auth.require("OWNER");var p=parlourFields(b);p.put("owner_id",uid);long pid=db.insert("parlours",p);db.insert("cancellation_policies",map("parlour_id",pid));return db.one("SELECT * FROM parlours WHERE parlour_id=?",pid);}
 @PutMapping("/api/owner/parlours/{pid}") @Transactional Map<String,Object> edit(@PathVariable long pid,@RequestBody Map<String,Object>b){auth.owner(pid);lock(pid);var fields=parlourFields(b);fields.put("status","PENDING");db.patch("parlours","parlour_id",pid,fields);return db.one("SELECT * FROM parlours WHERE parlour_id=?",pid);}
 Map<String,Object> parlourFields(Map<String,Object>b){var f=map("name",text(b,"name",160),"category",text(b,"category",50),"address",text(b,"address",500),"phone",Auth.phone(b),"description",String.valueOf(b.getOrDefault("description","")),"lat",Double.parseDouble(b.get("lat").toString()),"lng",Double.parseDouble(b.get("lng").toString()),"timezone",b.getOrDefault("timezone","Asia/Dhaka"));if(Math.abs((double)f.get("lat"))>90||Math.abs((double)f.get("lng"))>180)throw error(400,"Invalid coordinates");ZoneId.of(f.get("timezone").toString());return f;}
 void lock(long pid){db.one("SELECT parlour_id FROM parlours WHERE parlour_id=? FOR UPDATE",pid);}
 @GetMapping("/api/owner/parlours/{pid}/{table}") List<Map<String,Object>> records(@PathVariable long pid,@PathVariable String table){auth.owner(pid);resource(table);if(table.equals("staff_schedules"))return db.list("SELECT x.* FROM staff_schedules x JOIN staff s ON s.staff_id=x.staff_id WHERE s.parlour_id=?",pid);return db.list("SELECT * FROM "+table+" WHERE parlour_id=?",pid);}
 @PostMapping("/api/owner/parlours/{pid}/{table}") @Transactional Map<String,Object> add(@PathVariable long pid,@PathVariable String table,@RequestBody Map<String,Object>b){auth.owner(pid);lock(pid);var r=resource(table);var f=fields(pid,table,b);if(!table.equals("staff_schedules"))f.put("parlour_id",pid);long id=db.insert(table,f);return db.one("SELECT * FROM "+table+" WHERE "+r.pk()+"=?",id);}
 @PutMapping("/api/owner/parlours/{pid}/{table}/{id}") @Transactional Map<String,Object> change(@PathVariable long pid,@PathVariable String table,@PathVariable long id,@RequestBody Map<String,Object>b){auth.owner(pid);lock(pid);var r=resource(table);belongs(pid,table,id);db.patch(table,r.pk(),id,fields(pid,table,b));return db.one("SELECT * FROM "+table+" WHERE "+r.pk()+"=?",id);}
 @DeleteMapping("/api/owner/parlours/{pid}/{table}/{id}") @Transactional Map<String,Object> remove(@PathVariable long pid,@PathVariable String table,@PathVariable long id){auth.owner(pid);lock(pid);var r=resource(table);belongs(pid,table,id);if(List.of("services","staff").contains(table))db.update("UPDATE "+table+" SET status='INACTIVE' WHERE "+r.pk()+"=?",id);else if(table.equals("cancellation_policies"))throw error(400,"Edit the policy instead of deleting it");else db.update("DELETE FROM "+table+" WHERE "+r.pk()+"=?",id);return map("ok",true);}
 void belongs(long pid,String table,long id){var r=resource(table);String sql=table.equals("staff_schedules")?"SELECT COUNT(*) FROM staff_schedules x JOIN staff s ON x.staff_id=s.staff_id WHERE s.parlour_id=? AND x.schedule_id=?":"SELECT COUNT(*) FROM "+table+" WHERE parlour_id=? AND "+r.pk()+"=?";if(db.count(sql,pid,id)!=1)throw error(403,"Record is outside your parlour");}
 Map<String,Object> fields(long pid,String table,Map<String,Object>b){var f=new LinkedHashMap<String,Object>();for(String k:resource(table).fields())if(b.containsKey(k))f.put(k,b.get(k));if(f.isEmpty())throw error(400,"No editable fields");
  for(var e:f.entrySet()){String k=e.getKey();Object v=e.getValue();if(v==null){if(!k.equals("staff_id"))throw error(400,"Missing "+k);continue;}if(v instanceof String s&&s.length()>2048)throw error(400,"Field too long");if(k.equals("staff_id")){if(db.count("SELECT COUNT(*) FROM staff WHERE staff_id=? AND parlour_id=?",v,pid)!=1)throw error(400,"Unknown staff");}if(k.endsWith("_time"))e.setValue(java.sql.Time.valueOf(LocalTime.parse(v.toString())));if(k.equals("holiday_date"))e.setValue(java.sql.Date.valueOf(v.toString()));if(k.equals("start_at")||k.equals("end_at"))e.setValue(java.sql.Timestamp.from(Instant.parse(v.toString())));if(k.equals("image_url")&&!v.toString().startsWith("https://"))throw error(400,"Image URL must use HTTPS");if(k.equals("status")&&!Set.of("ACTIVE","INACTIVE").contains(v.toString()))throw error(400,"Invalid status");if(k.equals("reschedule_rule")&&!Set.of("ALLOWED","DISABLED").contains(v.toString()))throw error(400,"Invalid reschedule rule");}
  return f;
 }
 @PutMapping("/api/owner/parlours/{pid}/staff/{sid}/services") @Transactional Map<String,Object> assign(@PathVariable long pid,@PathVariable long sid,@RequestBody List<Long> ids){auth.owner(pid);lock(pid);belongs(pid,"staff",sid);if(ids.size()>100)throw error(400,"Too many services");for(long service:ids)belongs(pid,"services",service);db.update("DELETE FROM staff_services WHERE staff_id=?",sid);for(long service:new HashSet<>(ids))db.update("INSERT INTO staff_services(staff_id,service_id,expertise_level) VALUES (?,?,?)",sid,service,"QUALIFIED");return map("ok",true);}
}
