package com.parlour.management;
import static com.parlour.management.Db.*;
import java.util.*;
import java.time.*;
import java.sql.Timestamp;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.*;
@RestController
public class Payments {
 final Db db;final Bookings bookings;final Gateway gateway;final Auth auth;
 Payments(Db db,Bookings bookings,Gateway gateway,Auth auth){this.db=db;this.bookings=bookings;this.gateway=gateway;this.auth=auth;}
 @PostMapping("/api/payments/initiate") @Transactional(isolation=Isolation.READ_COMMITTED) Map<String,Object> initiate(@RequestBody Map<String,Object> body){long bid=Long.parseLong(body.get("booking_id").toString());var b=bookings.locked(bid);if(id(b,"customer_id")!=id(auth.current(),"user_id"))throw error(403,"Only the booking customer can pay");if(!"PENDING_PAYMENT".equals(b.get("status"))||Bookings.instant(b.get("hold_until")).isBefore(Instant.now()))throw error(409,"Payment hold expired or booking is already paid");var existing=db.list("SELECT * FROM payments WHERE booking_id=? ORDER BY payment_id DESC",bid);if(!existing.isEmpty()&&existing.get(0).get("checkout_url")!=null)return map("checkout_url",existing.get(0).get("checkout_url"));String tx="PB"+UUID.randomUUID().toString().replace("-","").substring(0,26);var response=gateway.initiate(b,tx,body);String url=String.valueOf(response.get("GatewayPageURL"));if(!"SUCCESS".equals(response.get("status"))||!url.startsWith("https://"))throw error(502,"Gateway could not start checkout");db.insert("payments",map("booking_id",bid,"transaction_id",tx,"amount",b.get("advance_amount"),"method","ONLINE","gateway","SSLCOMMERZ","status","PENDING","checkout_url",url));return map("checkout_url",url);}
 @PostMapping("/api/payments/callback") @Transactional(isolation=Isolation.READ_COMMITTED) Map<String,Object> callback(@RequestParam Map<String,String> body){String val=body.get("val_id");if(val==null||val.isBlank())return map("message","Payment not verified. Return to the app to check your booking.");if(val.length()>100)throw error(400,"Invalid validation ID");var verified=gateway.verify(val);return applyVerified(verified);}
 Map<String,Object> applyVerified(Map<String,Object> v){if(!Set.of("VALID","VALIDATED").contains(v.get("status")))throw error(400,"Payment not verified");var pay=db.one("SELECT * FROM payments WHERE transaction_id=?",v.get("tran_id"));long bid=id(pay,"booking_id");var b=db.one("SELECT * FROM bookings WHERE booking_id=?",bid);db.one("SELECT parlour_id FROM parlours WHERE parlour_id=? FOR UPDATE",id(b,"parlour_id"));pay=db.one("SELECT * FROM payments WHERE payment_id=? FOR UPDATE",id(pay,"payment_id"));b=db.one("SELECT * FROM bookings WHERE booking_id=?",bid);
  if(!"BDT".equals(v.get("currency"))||v.get("amount")==null||money(v.get("amount")).compareTo(money(pay.get("amount")))!=0||v.get("bank_tran_id")==null)throw error(400,"Payment amount or currency mismatch");if("PAID".equals(pay.get("status")))return map("message","Payment already recorded");db.update("UPDATE payments SET status='PAID',paid_at=?,bank_transaction_id=? WHERE payment_id=?",Timestamp.from(Instant.now()),v.get("bank_tran_id"),id(pay,"payment_id"));
  boolean safe="0".equals(String.valueOf(v.get("risk_level")));boolean alive="PENDING_PAYMENT".equals(b.get("status"))&&Bookings.instant(b.get("hold_until")).isAfter(Instant.now())&&Bookings.instant(b.get("start_at")).isAfter(Instant.now());
  if(safe&&alive){String next=yes(bookings.policy(b).get("owner_approval"))?"PENDING_OWNER":"CONFIRMED";db.update("UPDATE bookings SET status=? WHERE booking_id=?",next,bid);bookings.event(bid,"PAYMENT_VERIFIED","Payment verified","BDT "+pay.get("amount"));}
  else {if("PENDING_PAYMENT".equals(b.get("status")))db.update("UPDATE bookings SET status='EXPIRED' WHERE booking_id=?",bid);bookings.queueRefund(bid,money(pay.get("amount")),safe?"Payment arrived after reservation expired":"Gateway risk flag requires review");bookings.event(bid,"REFUND_PENDING","Payment needs review","The appointment was not confirmed. Contact the parlour.");}return map("message","Payment processed. Return to the app.");
 }
 @PostMapping("/api/owner/bookings/{bid}/cash-payment") @Transactional(isolation=Isolation.READ_COMMITTED) Map<String,Object> cash(@PathVariable long bid){auth.require("OWNER");var b=bookings.locked(bid);if(!Set.of("CONFIRMED","COMPLETED").contains(b.get("status")))throw error(409,"Cannot accept cash for this booking");var due=money(b.get("total_amount")).subtract(bookings.paid(bid));if(due.signum()>0)db.insert("payments",map("booking_id",bid,"transaction_id","CASH-"+bid,"amount",due,"method","CASH","gateway","OFFLINE","status","PAID","paid_at",Timestamp.from(Instant.now())));return bookings.detail(bid);}
}
