-- Proposal section 3.5. Core table/field names retained. No sample business records.
CREATE TABLE users (user_id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(254) UNIQUE,phone VARCHAR(30) UNIQUE,password_hash VARCHAR(100),role VARCHAR(16) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE parlours (parlour_id BIGINT AUTO_INCREMENT PRIMARY KEY,owner_id BIGINT NOT NULL,name VARCHAR(160) NOT NULL,category VARCHAR(50) NOT NULL,description TEXT,address VARCHAR(500) NOT NULL,lat DECIMAL(10,7) NOT NULL,lng DECIMAL(10,7) NOT NULL,phone VARCHAR(30) NOT NULL,rating DECIMAL(3,2) NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'PENDING',timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Dhaka',FOREIGN KEY(owner_id) REFERENCES users(user_id));
CREATE INDEX ix_parlours_location ON parlours(lat,lng);
CREATE TABLE parlour_images (image_id BIGINT AUTO_INCREMENT PRIMARY KEY,parlour_id BIGINT NOT NULL,image_url VARCHAR(2048) NOT NULL,type VARCHAR(20) NOT NULL,sort_order INT NOT NULL DEFAULT 0,FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id));
CREATE TABLE services (service_id BIGINT AUTO_INCREMENT PRIMARY KEY,parlour_id BIGINT NOT NULL,name VARCHAR(160) NOT NULL,description TEXT,duration_min INT NOT NULL,price DECIMAL(12,2) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',CHECK(duration_min BETWEEN 5 AND 720),CHECK(price>=0),FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id));
CREATE TABLE staff (staff_id BIGINT AUTO_INCREMENT PRIMARY KEY,parlour_id BIGINT NOT NULL,name VARCHAR(120) NOT NULL,designation VARCHAR(120),experience INT NOT NULL DEFAULT 0,specialization VARCHAR(500),rating DECIMAL(3,2) NOT NULL DEFAULT 0,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id));
CREATE TABLE staff_services (staff_id BIGINT NOT NULL,service_id BIGINT NOT NULL,expertise_level VARCHAR(40) NOT NULL,PRIMARY KEY(staff_id,service_id),FOREIGN KEY(staff_id) REFERENCES staff(staff_id),FOREIGN KEY(service_id) REFERENCES services(service_id));
CREATE TABLE staff_schedules (schedule_id BIGINT AUTO_INCREMENT PRIMARY KEY,staff_id BIGINT NOT NULL,day_of_week INT NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',CHECK(day_of_week BETWEEN 1 AND 7),CHECK(end_time>start_time),FOREIGN KEY(staff_id) REFERENCES staff(staff_id));
CREATE TABLE holidays (holiday_id BIGINT AUTO_INCREMENT PRIMARY KEY,parlour_id BIGINT NOT NULL,holiday_date DATE NOT NULL,reason VARCHAR(500),UNIQUE(parlour_id,holiday_date),FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id));
CREATE TABLE blocked_slots (block_id BIGINT AUTO_INCREMENT PRIMARY KEY,parlour_id BIGINT NOT NULL,staff_id BIGINT,start_at TIMESTAMP NOT NULL,end_at TIMESTAMP NOT NULL,reason VARCHAR(500),CHECK(end_at>start_at),FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id),FOREIGN KEY(staff_id) REFERENCES staff(staff_id));
CREATE TABLE cancellation_policies (policy_id BIGINT AUTO_INCREMENT PRIMARY KEY,parlour_id BIGINT NOT NULL UNIQUE,advance_required BOOLEAN NOT NULL DEFAULT FALSE,min_advance_pct INT NOT NULL DEFAULT 0,cancel_window_hr INT NOT NULL DEFAULT 24,fee_pct INT NOT NULL DEFAULT 0,refund_pct INT NOT NULL DEFAULT 100,reschedule_rule VARCHAR(20) NOT NULL DEFAULT 'ALLOWED',manual_approval BOOLEAN NOT NULL DEFAULT FALSE,owner_approval BOOLEAN NOT NULL DEFAULT FALSE,CHECK(min_advance_pct BETWEEN 0 AND 100),CHECK(fee_pct BETWEEN 0 AND 100),CHECK(refund_pct BETWEEN 0 AND 100),CHECK(cancel_window_hr>=0),CHECK(NOT advance_required OR min_advance_pct>0),FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id));
CREATE TABLE bookings (booking_id BIGINT AUTO_INCREMENT PRIMARY KEY,customer_name VARCHAR(120) NOT NULL,customer_phone VARCHAR(30) NOT NULL,parlour_id BIGINT NOT NULL,staff_id BIGINT,booking_date DATE NOT NULL,start_at TIMESTAMP NOT NULL,end_at TIMESTAMP NOT NULL,total_amount DECIMAL(12,2) NOT NULL,advance_amount DECIMAL(12,2) NOT NULL,status VARCHAR(24) NOT NULL,customer_id BIGINT NOT NULL,idempotency_key VARCHAR(100) NOT NULL,request_hash VARCHAR(64) NOT NULL,hold_until TIMESTAMP,policy_snapshot TEXT NOT NULL,cancel_refund_quote DECIMAL(12,2),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(customer_id,idempotency_key),CHECK(end_at>start_at),FOREIGN KEY(customer_id) REFERENCES users(user_id),FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id),FOREIGN KEY(staff_id) REFERENCES staff(staff_id));
CREATE INDEX ix_bookings_slot ON bookings(parlour_id,staff_id,start_at,end_at,status);
CREATE INDEX ix_bookings_date ON bookings(booking_date,status);
CREATE TABLE booking_items (booking_item_id BIGINT AUTO_INCREMENT PRIMARY KEY,booking_id BIGINT NOT NULL,service_id BIGINT NOT NULL,price DECIMAL(12,2) NOT NULL,duration_min INT NOT NULL,FOREIGN KEY(booking_id) REFERENCES bookings(booking_id),FOREIGN KEY(service_id) REFERENCES services(service_id));
CREATE TABLE payments (payment_id BIGINT AUTO_INCREMENT PRIMARY KEY,booking_id BIGINT NOT NULL,transaction_id VARCHAR(100) NOT NULL UNIQUE,amount DECIMAL(12,2) NOT NULL,method VARCHAR(30) NOT NULL,gateway VARCHAR(30) NOT NULL,status VARCHAR(24) NOT NULL,paid_at TIMESTAMP,bank_transaction_id VARCHAR(160) UNIQUE,checkout_url VARCHAR(2048),FOREIGN KEY(booking_id) REFERENCES bookings(booking_id));
CREATE TABLE ratings (rating_id BIGINT AUTO_INCREMENT PRIMARY KEY,booking_id BIGINT NOT NULL,parlour_id BIGINT NOT NULL,staff_id BIGINT,score INT NOT NULL,review VARCHAR(2000),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,target_type VARCHAR(16) NOT NULL,UNIQUE(booking_id,target_type),CHECK(score BETWEEN 1 AND 5),FOREIGN KEY(booking_id) REFERENCES bookings(booking_id),FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id),FOREIGN KEY(staff_id) REFERENCES staff(staff_id));
CREATE TABLE notifications (notification_id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT,booking_id BIGINT,type VARCHAR(40) NOT NULL,title VARCHAR(120) NOT NULL,body VARCHAR(1000) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'PENDING',sent_at TIMESTAMP,attempts INT NOT NULL DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(user_id),FOREIGN KEY(booking_id) REFERENCES bookings(booking_id));
CREATE TABLE admin_actions (action_id BIGINT AUTO_INCREMENT PRIMARY KEY,admin_id BIGINT NOT NULL,target_type VARCHAR(40) NOT NULL,target_id BIGINT NOT NULL,action VARCHAR(40) NOT NULL,reason VARCHAR(1000) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(admin_id) REFERENCES users(user_id));
-- Supporting tables required by hours, push delivery and administrative features.
CREATE TABLE business_hours (hours_id BIGINT AUTO_INCREMENT PRIMARY KEY,parlour_id BIGINT NOT NULL,day_of_week INT NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,UNIQUE(parlour_id,day_of_week),CHECK(day_of_week BETWEEN 1 AND 7),CHECK(end_time>start_time),FOREIGN KEY(parlour_id) REFERENCES parlours(parlour_id));
CREATE TABLE device_tokens (token VARCHAR(512) PRIMARY KEY,user_id BIGINT NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(user_id));
CREATE TABLE complaints (complaint_id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,booking_id BIGINT NOT NULL,body VARCHAR(2000) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'OPEN',resolution VARCHAR(2000),FOREIGN KEY(user_id) REFERENCES users(user_id),FOREIGN KEY(booking_id) REFERENCES bookings(booking_id));
CREATE TABLE categories (category_id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) UNIQUE NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE banners (banner_id BIGINT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(160) NOT NULL,image_url VARCHAR(2048) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE refund_requests (refund_id BIGINT AUTO_INCREMENT PRIMARY KEY,payment_id BIGINT NOT NULL UNIQUE,amount DECIMAL(12,2) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'PENDING',gateway_reference VARCHAR(160),reason VARCHAR(500) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(payment_id) REFERENCES payments(payment_id));
