package com.parlour.management;
import android.Manifest;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import android.app.DatePickerDialog;
import androidx.appcompat.app.*;
import androidx.lifecycle.ViewModelProvider;
import androidx.core.app.ActivityCompat;
import com.google.android.gms.location.LocationServices;
import com.google.firebase.messaging.FirebaseMessaging;
import com.parlour.management.databinding.ActivityMainBinding;
import org.json.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.function.Consumer;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

public class MainActivity extends AppCompatActivity {
 ActivityMainBinding ui;AppViewModel vm;LinearLayout content;Map<String,Consumer<Object>> callbacks=new HashMap<>();String role="CUSTOMER";JSONObject selected;Set<Long> serviceIds=new LinkedHashSet<>();Long preferredStaff=null;String zone="Asia/Dhaka";double lat=Double.NaN,lng=Double.NaN;long ownerPid=0;final Handler handler=new Handler(Looper.getMainLooper());Runnable slotRefresh;
 @Override public void onCreate(Bundle saved){super.onCreate(saved);ui=ActivityMainBinding.inflate(getLayoutInflater());setContentView(ui.getRoot());content=ui.content;vm=new ViewModelProvider(this).get(AppViewModel.class);role=vm.repository.role();FirebaseSession.sync(vm.repository);ui.home.setOnClickListener(v->home());ui.account.setOnClickListener(v->account());ui.bookings.setOnClickListener(v->myBookings());ui.inbox.setOnClickListener(v->inbox());vm.loading.observe(this,v->ui.loading.setVisibility(Boolean.TRUE.equals(v)?View.VISIBLE:View.GONE));vm.results.observe(this,r->{if(r==null||r.consumed)return;r.consumed=true;var cb=callbacks.remove(r.key);if(r.error!=null)message(r.error);else if(cb!=null)cb.accept(r.value);});if(vm.repository.base().isEmpty())connection();else start();}
 @Override protected void onStop(){super.onStop();if(slotRefresh!=null)handler.removeCallbacks(slotRefresh);}
 void call(String method,String path,Object body,String key,Consumer<Object> cb){String tag=UUID.randomUUID().toString();callbacks.put(tag,cb);vm.call(tag,method,path,body,key);}
 void get(String path,Consumer<Object> cb){call("GET",path,null,null,cb);}void post(String path,Object body,Consumer<Object> cb){call("POST",path,body,null,cb);}
 static JSONObject obj(Object... pairs){JSONObject b=new JSONObject();try{for(int i=0;i<pairs.length;i+=2)b.put((String)pairs[i],pairs[i+1]==null?JSONObject.NULL:pairs[i+1]);}catch(JSONException e){throw new IllegalArgumentException(e);}return b;}
 static String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(java.io.UnsupportedEncodingException e){throw new IllegalStateException(e);}}
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density);}
 void clear(String title,String subtitle){if(slotRefresh!=null){handler.removeCallbacks(slotRefresh);slotRefresh=null;}content.removeAllViews();label(title,28,true);if(!subtitle.isBlank())label(subtitle,15,false);}
 void label(String text,int size,boolean bold){TextView t=new TextView(this);t.setText(text);t.setTextSize(size);t.setTextColor(Color.parseColor(bold?"#30202A":"#786973"));if(bold)t.setTypeface(null,1);t.setPadding(0,dp(7),0,dp(12));content.addView(t);}
 Button button(String text,Runnable action){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setMinHeight(dp(52));content.addView(b,new LinearLayout.LayoutParams(-1,-2));b.setOnClickListener(v->{try{action.run();}catch(Exception e){message(e.getMessage()==null?"Check the entered details":e.getMessage());}});return b;}
 EditText field(String hint,String value,int type){var wrap=new com.google.android.material.textfield.TextInputLayout(this);wrap.setHint(hint);var e=new com.google.android.material.textfield.TextInputEditText(this);e.setText(value);e.setInputType(type);wrap.addView(e);var lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(12);content.addView(wrap,lp);return e;}
 EditText field(String hint){return field(hint,"",InputType.TYPE_CLASS_TEXT);}
 Spinner spinner(String title,String[] choices){label(title,14,true);Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,choices));content.addView(s,new LinearLayout.LayoutParams(-1,dp(52)));return s;}
 void message(String s){new AlertDialog.Builder(this).setTitle("Parlour Booking").setMessage(s).setPositiveButton("OK",null).show();}
 String value(EditText e){return e.getText()==null?"":e.getText().toString().trim();}
 void connection(){clear("Connect your app","Enter the address of your running booking server. Your business data stays on that server.");EditText url=field("Backend URL",vm.repository.base(),InputType.TYPE_TEXT_VARIATION_URI);button("Connect",()->{FirebaseSession.signOut();vm.repository.setBase(value(url));start();});label("For Android Emulator with a local server: http://10.0.2.2:8080\nFor your phone: use a reachable HTTPS server or your computer’s LAN address for this debug build.",14,false);}
 void start(){if(vm.repository.token().isEmpty())post("/api/auth/guest",obj(),r->{saveSession((JSONObject)r);home();});else home();}
 void saveSession(JSONObject data){try{vm.repository.session(data);role=vm.repository.role();FirebaseSession.sync(vm.repository);FirebaseMessaging.getInstance().getToken().addOnSuccessListener(t->vm.repository.request("POST","/api/device-token",obj("token",t),null,(a,b)->{}));}catch(Exception e){message("Could not save the session");}}
 void home(){if(vm.repository.base().isEmpty()){connection();return;}role=vm.repository.role();if(role.equals("OWNER")){ownerHome();return;}clear("A little time for you","Find a parlour, choose your service and book a time that fits.");EditText query=field("Search by parlour or area");Spinner category=spinner("Category",new String[]{"All","MEN","WOMEN","UNISEX"}),sort=spinner("Sort by",new String[]{"rating","distance","price","popularity"});EditText radius=field("Search radius (km)","10",InputType.TYPE_CLASS_NUMBER);button("Use current location",this::location);button("Find parlours",()->search(value(query),category.getSelectedItem().toString(),sort.getSelectedItem().toString(),value(radius)));button("Browse all parlours",()->search("","All","rating","10"));}
 void location(){if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.ACCESS_FINE_LOCATION},12);return;}LocationServices.getFusedLocationProviderClient(this).getCurrentLocation(com.google.android.gms.location.Priority.PRIORITY_BALANCED_POWER_ACCURACY,null).addOnSuccessListener(l->{if(l==null){message("Location unavailable. Search using an area name.");return;}lat=l.getLatitude();lng=l.getLongitude();search("","All","distance","10");}).addOnFailureListener(e->message("Location unavailable. Use manual search."));}
 @Override public void onRequestPermissionsResult(int code,String[]permissions,int[]results){super.onRequestPermissionsResult(code,permissions,results);if(code==12&&results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)location();}
 void search(String q,String category,String sort,String radius){String path="/api/public/parlours?q="+enc(q)+"&category="+enc(category.equals("All")?"":category)+"&sort="+sort+"&radius="+enc(radius);if(!Double.isNaN(lat))path+="&lat="+lat+"&lng="+lng;get(path,r->{clear("Find your next appointment","Results from registered, verified parlours.");JSONArray rows=(JSONArray)r;if(rows.length()==0)label("No parlours found. Try another area or a larger radius.",18,true);for(int i=0;i<rows.length();i++){JSONObject p=rows.optJSONObject(i);button(p.optString("name")+"  ·  ★ "+p.optString("rating")+"\n"+p.optString("address")+"\nFrom ৳"+p.optString("starting_price","—")+(!p.has("distance_km")?"":" · "+String.format(Locale.US,"%.1f km",p.optDouble("distance_km"))),()->details(p.optLong("parlour_id")));}});}
 void details(long pid){get("/api/public/parlours/"+pid,r->{selected=(JSONObject)r;serviceIds.clear();preferredStaff=null;zone=selected.optString("timezone","Asia/Dhaka");clear(selected.optString("name"),selected.optString("address"));label(selected.optString("description"),16,false);label("★ "+selected.optString("rating")+"   •   "+selected.optString("category"),15,true);button("Directions",()->open("https://www.google.com/maps/dir/?api=1&destination="+selected.optDouble("lat")+","+selected.optDouble("lng")));button("Call parlour",()->startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+selected.optString("phone")))));JSONArray hours=selected.optJSONArray("business_hours");if(hours!=null)for(int i=0;i<hours.length();i++){JSONObject h=hours.optJSONObject(i);label(DayOfWeek.of(h.optInt("day_of_week")).toString()+"  "+h.optString("start_time")+"–"+h.optString("end_time"),13,false);}label("Choose your services",22,true);JSONArray services=selected.optJSONArray("services");if(services!=null)for(int i=0;i<services.length();i++){JSONObject s=services.optJSONObject(i);CheckBox c=new CheckBox(this);c.setText(s.optString("name")+"  ·  ৳"+s.optString("price")+"\n"+s.optInt("duration_min")+" min · "+s.optString("description",""));c.setMinHeight(dp(60));content.addView(c);c.setOnCheckedChangeListener((v,checked)->{if(checked)serviceIds.add(s.optLong("service_id"));else serviceIds.remove(s.optLong("service_id"));});}JSONArray staff=selected.optJSONArray("staff");ArrayList<String>names=new ArrayList<>();names.add("Any qualified staff");if(staff!=null)for(int i=0;i<staff.length();i++){JSONObject s=staff.optJSONObject(i);names.add(s.optString("name")+" · "+s.optString("designation")+" · ★ "+s.optString("rating"));}Spinner who=spinner("Staff preference",names.toArray(new String[0]));button("Choose appointment time",()->{if(serviceIds.isEmpty()){message("Choose at least one service");return;}preferredStaff=who.getSelectedItemPosition()==0?null:staff.optJSONObject(who.getSelectedItemPosition()-1).optLong("staff_id");chooseDate(pid,null);});JSONArray policies=selected.optJSONArray("cancellation_policies");if(policies!=null&&policies.length()>0){JSONObject p=policies.optJSONObject(0);label("Booking policy",20,true);label("Cancellation window: "+p.optInt("cancel_window_hr")+" hours\nLate cancellation fee: "+p.optInt("fee_pct")+"%\nEligible refund: "+p.optInt("refund_pct")+"%\nAdvance payment: "+(p.optBoolean("advance_required")?p.optInt("min_advance_pct")+"% required":"Optional"),15,false);}});}
 void chooseDate(long pid,Long bid){LocalDate now=LocalDate.now(ZoneId.of(zone));DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->slots(pid,LocalDate.of(y,m+1,day),bid),now.getYear(),now.getMonthValue()-1,now.getDayOfMonth());d.getDatePicker().setMinDate(System.currentTimeMillis());d.getDatePicker().setMaxDate(System.currentTimeMillis()+90L*86400000);d.show();}
 void slots(long pid,LocalDate day,Long bid){String ids=String.join(",",serviceIds.stream().map(String::valueOf).toArray(String[]::new));get("/api/public/parlours/"+pid+"/availability?services="+ids+"&date="+day+(preferredStaff==null?"":"&staff="+preferredStaff),r->{JSONObject data=(JSONObject)r;clear("Choose a time",day+" · "+data.optString("timezone")+"\n"+data.optInt("duration_min")+" minutes · ৳"+data.optString("total_amount"));button("Choose another date",()->chooseDate(pid,bid));JSONArray available=data.optJSONArray("slots");if(available==null||available.length()==0)label("No slots available. Try another day or staff member.",18,true);else for(int i=0;i<available.length();i++){JSONObject slot=available.optJSONObject(i);String display=Instant.parse(slot.optString("start_at")).atZone(ZoneId.of(zone)).format(DateTimeFormatter.ofPattern("h:mm a"));button(display,()->{if(bid==null)summary(pid,slot,data);else post("/api/bookings/"+bid+"/reschedule",obj("start_at",slot.optString("start_at"),"staff_id",slot.optLong("staff_id")),x->booking(bid));});}button("Refresh availability",()->slots(pid,day,bid));});}
 void summary(long pid,JSONObject slot,JSONObject price){clear("Your appointment","৳"+price.optString("total_amount")+" · "+price.optInt("duration_min")+" minutes\n"+Instant.parse(slot.optString("start_at")).atZone(ZoneId.of(zone)).format(DateTimeFormatter.ofPattern("EEE, d MMM · h:mm a")));EditText name=field("Your name"),phone=field("Phone number","",InputType.TYPE_CLASS_PHONE);Spinner method=spinner("Payment method",new String[]{"AT_PARLOUR","ONLINE"});String key=UUID.randomUUID().toString();button("Confirm booking",()->{JSONObject body=obj("parlour_id",pid,"services",new JSONArray(serviceIds),"staff_id",slot.optLong("staff_id"),"start_at",slot.optString("start_at"),"customer_name",value(name),"customer_phone",value(phone),"payment_method",method.getSelectedItem().toString());call("POST","/api/bookings",body,key,r->booking(((JSONObject)r).optLong("booking_id")));});}
 void myBookings(){if(vm.repository.token().isEmpty()){start();return;}get(role.equals("OWNER")?"/api/owner/bookings":"/api/bookings",r->{clear("Your appointments","Tap an appointment for its receipt and available actions.");JSONArray a=(JSONArray)r;if(a.length()==0)label("No appointments yet.",20,true);for(int i=0;i<a.length();i++){JSONObject b=a.optJSONObject(i);button("#"+b.optLong("booking_id")+" · "+b.optString("status")+"\n"+b.optString("start_at")+" · ৳"+b.optString("total_amount"),()->booking(b.optLong("booking_id")));}});}
 void booking(long bid){get("/api/bookings/"+bid,r->{JSONObject b=(JSONObject)r;clear("Appointment #"+bid,b.optString("status"));label(b.optString("customer_name")+"\n"+b.optString("start_at")+"\nTotal: ৳"+b.optString("total_amount"),19,true);JSONArray items=b.optJSONArray("items");if(items!=null)for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);label(item.optString("name")+" · ৳"+item.optString("price")+" · "+item.optInt("duration_min")+" min",16,false);}JSONArray payments=b.optJSONArray("payments");if(payments!=null)for(int i=0;i<payments.length();i++){JSONObject p=payments.optJSONObject(i);label(p.optString("method")+" · "+p.optString("status")+" · ৳"+p.optString("amount"),15,false);}button("Refresh status",()->booking(bid));if(b.optString("status").equals("PENDING_PAYMENT"))button("Continue to payment",()->checkout(bid));if(List.of("CONFIRMED","PENDING_OWNER","PENDING_PAYMENT").contains(b.optString("status")))button("Cancel appointment",()->new AlertDialog.Builder(this).setTitle("Cancel this appointment?").setMessage("The cancellation policy saved with your booking will determine fees and any refund.").setNegativeButton("Keep booking",null).setPositiveButton("Request cancellation",(d,w)->post("/api/bookings/"+bid+"/cancel",obj(),x->booking(bid))).show());if(b.optString("status").equals("CONFIRMED"))button("Reschedule",()->{serviceIds.clear();if(items!=null)for(int i=0;i<items.length();i++)serviceIds.add(items.optJSONObject(i).optLong("service_id"));preferredStaff=null;get("/api/public/parlours/"+b.optLong("parlour_id"),p->{zone=((JSONObject)p).optString("timezone","Asia/Dhaka");chooseDate(b.optLong("parlour_id"),bid);});});if(role.equals("OWNER")){if(b.optString("status").equals("PENDING_OWNER")){button("Accept appointment",()->ownerStatus(bid,"CONFIRMED"));button("Reject appointment",()->ownerStatus(bid,"REJECTED"));}if(b.optString("status").equals("CANCEL_PENDING"))button("Approve cancellation",()->ownerStatus(bid,"CANCELLED"));if(b.optString("status").equals("CONFIRMED"))button("Mark completed",()->ownerStatus(bid,"COMPLETED"));if(List.of("CONFIRMED","COMPLETED").contains(b.optString("status")))button("Record cash received",()->new AlertDialog.Builder(this).setMessage("Confirm you have received the outstanding balance in cash.").setNegativeButton("Back",null).setPositiveButton("Cash received",(d,w)->post("/api/owner/bookings/"+bid+"/cash-payment",obj(),x->booking(bid))).show());}else{if(b.optString("status").equals("COMPLETED"))button("Write a review",()->review(bid));button("Report an issue",()->complaint(bid));}button("Share receipt",()->{String receipt="Parlour Booking #"+bid+"\n"+b.optString("status")+"\n"+b.optString("start_at")+"\nTotal BDT "+b.optString("total_amount");startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,receipt),"Share receipt"));});});}
 void ownerStatus(long bid,String status){post("/api/owner/bookings/"+bid+"/status",obj("status",status),r->booking(bid));}
 void checkout(long bid){clear("Payment details","SSLCommerz will open in your browser. Return here to refresh the booking after payment.");EditText email=field("Email address"),address=field("Billing address"),city=field("City"),country=field("Country","Bangladesh",InputType.TYPE_CLASS_TEXT);button("Open secure checkout",()->post("/api/payments/initiate",obj("booking_id",bid,"email",value(email),"address",value(address),"city",value(city),"country",value(country)),r->open(((JSONObject)r).optString("checkout_url"))));button("Return to appointment",()->booking(bid));}
 void review(long bid){clear("How was your visit?","Reviews are available after the appointment is completed.");Spinner target=spinner("Review",new String[]{"PARLOUR","STAFF"}),score=spinner("Rating",new String[]{"5","4","3","2","1"});EditText review=field("Tell us about your visit");button("Submit review",()->post("/api/ratings",obj("booking_id",bid,"target_type",target.getSelectedItem(),"score",Integer.parseInt(score.getSelectedItem().toString()),"review",value(review)),r->booking(bid)));}
 void complaint(long bid){clear("Report an issue","Your complaint will be sent to the platform administrator.");EditText body=field("What happened?");button("Submit",()->post("/api/complaints",obj("booking_id",bid,"body",value(body)),r->{message("Complaint submitted");booking(bid);}));}
 void inbox(){get("/api/notifications",r->{clear("Updates","Booking and payment notifications.");button("Enable push notifications",()->{if(Build.VERSION.SDK_INT>=33)ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.POST_NOTIFICATIONS},13);});JSONArray a=(JSONArray)r;for(int i=0;i<a.length();i++){JSONObject n=a.optJSONObject(i);button(n.optString("title")+"\n"+n.optString("body"),()->booking(n.optLong("booking_id")));}if(a.length()==0)label("You’re all caught up.",20,true);});}
 void account(){clear("Your space","Manage your connection or access your business.");button("Connection",this::connection);if(role.equals("OWNER"))button("Business dashboard",this::ownerHome);else{button("Owner sign in",()->login(false));button("Register as an owner",()->login(true));}button("Switch to customer mode",()->{vm.repository.logout();FirebaseSession.sync(vm.repository);role="CUSTOMER";start();});}
 void login(boolean register){clear(register?"Create your owner account":"Welcome back","Manage your parlour’s appointments and services.");EditText name=register?field("Full name"):null,email=field("Email","",InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS),phone=register?field("Phone","",InputType.TYPE_CLASS_PHONE):null,password=field("Password (12+ characters)","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);button(register?"Create account":"Sign in",()->post(register?"/api/auth/register":"/api/auth/login",register?obj("name",value(name),"email",value(email),"phone",value(phone),"password",value(password)):obj("email",value(email),"password",value(password)),r->{saveSession((JSONObject)r);if(role.equals("ADMIN")){message("Use the web administration panel at your backend’s /admin/ address.");account();}else home();}));}
 void open(String url){Uri u=Uri.parse(url);if(!"https".equals(u.getScheme())){message("A secure link is required");return;}try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(ActivityNotFoundException e){message("Install a browser or maps app to open this link");}}
 void ownerHome(){get("/api/owner/parlours",r->{clear("Your business","Manage your profile, staff and appointments.");button("Register a parlour",()->parlourForm(null));button("View appointments",this::myBookings);JSONArray a=(JSONArray)r;for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);button(p.optString("name")+" · "+p.optString("status"),()->ownerParlour(p));}});}
 void ownerParlour(JSONObject p){ownerPid=p.optLong("parlour_id");clear(p.optString("name"),"Verification: "+p.optString("status"));button("Edit business profile",()->parlourForm(p));String[][] sections={{"Services","services"},{"Staff","staff"},{"Working hours","business_hours"},{"Staff schedules","staff_schedules"},{"Holidays","holidays"},{"Blocked times","blocked_slots"},{"Photo gallery","parlour_images"},{"Booking policy","cancellation_policies"}};for(String[]s:sections)button(s[0],()->resources(s[1]));button("Assign staff to services",this::assignStaff);}
 void parlourForm(JSONObject existing){JSONObject p=existing==null?obj():existing;clear(existing==null?"Register your parlour":"Business profile","Profile changes require administrator verification before public listing.");Map<String,EditText> fields=new LinkedHashMap<>();for(String k:new String[]{"name","category","address","phone","lat","lng","description","timezone"})fields.put(k,field(k.replace('_',' '),p.optString(k,k.equals("timezone")?"Asia/Dhaka":""),InputType.TYPE_CLASS_TEXT));button("Save profile",()->{JSONObject body=obj();for(var e:fields.entrySet())put(body,e.getKey(),value(e.getValue()));call(existing==null?"POST":"PUT","/api/owner/parlours"+(existing==null?"":"/"+p.optLong("parlour_id")),body,null,r->ownerHome());});}
 static void put(JSONObject o,String k,Object value){try{o.put(k,value==null?JSONObject.NULL:value);}catch(JSONException e){throw new IllegalArgumentException(e);}}
 static final Map<String,String> FORM=Map.of("services","name description duration_min price status","staff","name designation experience specialization status","business_hours","day_of_week start_time end_time","staff_schedules","staff_id day_of_week start_time end_time status","holidays","holiday_date reason","blocked_slots","staff_id start_at end_at reason","parlour_images","image_url type sort_order","cancellation_policies","advance_required min_advance_pct cancel_window_hr fee_pct refund_pct reschedule_rule manual_approval owner_approval");
 static final Map<String,String> PRIMARY=Map.of("services","service_id","staff","staff_id","business_hours","hours_id","staff_schedules","schedule_id","holidays","holiday_id","blocked_slots","block_id","parlour_images","image_id","cancellation_policies","policy_id");
 void resources(String table){get("/api/owner/parlours/"+ownerPid+"/"+table,r->{clear(table.replace('_',' '),"Create and update the records used for appointment availability.");if(!table.equals("cancellation_policies"))button("Add new",()->resourceForm(table,null));JSONArray a=(JSONArray)r;if(a.length()==0)label("No records yet.",18,true);for(int i=0;i<a.length();i++){JSONObject row=a.optJSONObject(i);String summary=row.optString("name",row.optString("reason",row.optString("start_time",row.optString("reschedule_rule","Record"))));button("#"+row.optLong(PRIMARY.get(table))+" · "+summary,()->resourceForm(table,row));}});}
 void resourceForm(String table,JSONObject row){clear(row==null?"Add record":"Edit record",table.replace('_',' '));if(table.equals("staff_schedules"))label("Use the staff ID shown in Staff. Days: Monday = 1 through Sunday = 7.",14,false);if(table.equals("blocked_slots"))label("Times use ISO format, for example 2026-10-01T10:00:00+06:00. Leave staff ID blank to block the whole parlour.",14,false);if(table.equals("business_hours")||table.equals("staff_schedules"))label("Hours use 24-hour time, for example 09:00 and 18:00. Overnight shifts must be split by day.",14,false);if(table.equals("holidays"))label("Enter the date as YYYY-MM-DD.",14,false);Map<String,EditText> fields=new LinkedHashMap<>();Map<String,CheckBox> booleans=new LinkedHashMap<>();for(String k:FORM.get(table).split(" ")){if(Set.of("advance_required","manual_approval","owner_approval").contains(k)){CheckBox c=new CheckBox(this);c.setText(k.replace('_',' '));c.setChecked(row!=null&&row.optBoolean(k));content.addView(c);booleans.put(k,c);}else{String fallback=k.equals("status")?"ACTIVE":k.equals("reschedule_rule")?"ALLOWED":k.equals("refund_pct")?"100":k.equals("cancel_window_hr")?"24":Set.of("experience","min_advance_pct","fee_pct","sort_order").contains(k)?"0":"";fields.put(k,field(k.replace('_',' '),row==null?fallback:row.optString(k,fallback),InputType.TYPE_CLASS_TEXT));}}button("Save",()->{JSONObject body=obj();for(var e:fields.entrySet()){String k=e.getKey(),v=value(e.getValue());if(k.equals("staff_id")&&v.isBlank()){put(body,k,null);continue;}if(Set.of("duration_min","price","experience","day_of_week","staff_id","sort_order","min_advance_pct","cancel_window_hr","fee_pct","refund_pct").contains(k))put(body,k,Double.parseDouble(v));else put(body,k,v);}for(var e:booleans.entrySet())put(body,e.getKey(),e.getValue().isChecked());call(row==null?"POST":"PUT","/api/owner/parlours/"+ownerPid+"/"+table+(row==null?"":"/"+row.optLong(PRIMARY.get(table))),body,null,r->resources(table));});if(row!=null&&!table.equals("cancellation_policies"))button("Remove record",()->new AlertDialog.Builder(this).setMessage("Remove this record? Services and staff will be deactivated to preserve booking history.").setNegativeButton("Keep",null).setPositiveButton("Remove",(d,w)->call("DELETE","/api/owner/parlours/"+ownerPid+"/"+table+"/"+row.optLong(PRIMARY.get(table)),null,null,r->resources(table))).show());}
 void assignStaff(){get("/api/owner/parlours/"+ownerPid+"/staff",r->{JSONArray staff=(JSONArray)r;get("/api/owner/parlours/"+ownerPid+"/services",s->{clear("Staff expertise","Choose a staff member and all services they are qualified to deliver. Saving replaces their assignments.");if(staff.length()==0){label("Add staff first.",18,true);return;}String[] names=new String[staff.length()];for(int i=0;i<staff.length();i++)names[i]=staff.optJSONObject(i).optString("name");Spinner person=spinner("Staff",names);Set<Long> ids=new LinkedHashSet<>();JSONArray services=(JSONArray)s;for(int i=0;i<services.length();i++){JSONObject item=services.optJSONObject(i);CheckBox c=new CheckBox(this);c.setText(item.optString("name"));content.addView(c);c.setOnCheckedChangeListener((v,checked)->{if(checked)ids.add(item.optLong("service_id"));else ids.remove(item.optLong("service_id"));});}button("Save expertise",()->call("PUT","/api/owner/parlours/"+ownerPid+"/staff/"+staff.optJSONObject(person.getSelectedItemPosition()).optLong("staff_id")+"/services",new JSONArray(ids),null,x->ownerHome()));});});}
}
